name = "MutationEntropy"
uuid = "f850fdbc-4888-4fdd-8207-963e142618af"
authors = ["Shiqinrui Xu <sxu128@connect.hkust-gz.edu.cn> and contributors"]
version = "1.0.0-DEV"

[deps]
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SwarmMakie = "0b1c068e-6a84-4e66-8136-5c95cafa83ed"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Colors = "0.13.1"
Dates = "1.11.0"
LinearAlgebra = "1.11.0"
SwarmMakie = "0.1.5"
TOML = "1.0.3"
